<a href="https://colab.research.google.com/github/vikhyatjagawat/tensorflow/blob/main/tensorflow_input_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf

In [17]:
numbers = [21, 22, 31, 45, 6, 7, 87]

In [18]:
tf_dataset = tf.data.Dataset.from_tensor_slices(numbers)

In [19]:
for i in tf_dataset:
  print(i)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(45, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(87, shape=(), dtype=int32)


In [20]:
for i in tf_dataset.take(3):
  print(i)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [21]:
tf_data_filter = tf_dataset.filter(lambda x: x>10)
for i in tf_data_filter:
  print(i)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(45, shape=(), dtype=int32)
tf.Tensor(87, shape=(), dtype=int32)


In [22]:
tf_data_map = tf_dataset.map(lambda x: x*100)
for i in tf_data_map:
  print(i)

tf.Tensor(2100, shape=(), dtype=int32)
tf.Tensor(2200, shape=(), dtype=int32)
tf.Tensor(3100, shape=(), dtype=int32)
tf.Tensor(4500, shape=(), dtype=int32)
tf.Tensor(600, shape=(), dtype=int32)
tf.Tensor(700, shape=(), dtype=int32)
tf.Tensor(8700, shape=(), dtype=int32)


In [23]:
for batch in tf_dataset.batch(3):
  print(batch)

tf.Tensor([21 22 31], shape=(3,), dtype=int32)
tf.Tensor([45  6  7], shape=(3,), dtype=int32)
tf.Tensor([87], shape=(1,), dtype=int32)


In [24]:
train_size = int(len(tf_dataset)*.8)
train_size

5

In [25]:
train_ds = tf_dataset.take(train_size)
test_ds = tf_dataset.skip(train_size)